# Generated by Django 5.1.15 on 2026-06-18 14:55

import apps.common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('conteudo', apps.common.fields.EncryptedTextField(verbose_name='conteúdo')),
                ('compartilhar_com_psicologa', models.BooleanField(default=False, verbose_name='compartilhar com a psicóloga')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patients.patient')),
            ],
            options={
                'verbose_name': 'anotação do paciente',
                'verbose_name_plural': 'anotações do paciente',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['patient', '-updated_at'], name='note_patient_updated_idx')],
            },
        ),
    ]
