# Generated by Django 5.1.15 on 2026-06-29 12:39

import apps.common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('conteudo', apps.common.fields.EncryptedTextField(verbose_name='evolução clínica')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_record', to='scheduling.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'evolução clínica',
                'verbose_name_plural': 'evoluções clínicas',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['patient', '-created_at'], name='record_patient_created_idx')],
            },
        ),
    ]
