# Generated by Django 5.1.15 on 2026-06-18 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=12)),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='patients.patient')),
            ],
            options={
                'verbose_name': 'tarefa terapêutica',
                'verbose_name_plural': 'tarefas terapêuticas',
                'ordering': ('status', 'prazo', '-created_at'),
                'indexes': [models.Index(fields=['patient', 'status'], name='hw_patient_status_idx')],
            },
        ),
    ]
