# Generated by Django 5.1.15 on 2026-07-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Falha de login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Cadastro'), ('PASSWORD_RESET_REQUEST', 'Solicitação de redefinição de senha'), ('PASSWORD_RESET', 'Redefinição de senha'), ('CONSENT_ACCEPTED', 'Consentimento aceito'), ('DATA_EXPORT', 'Exportação de dados pessoais')], max_length=40),
        ),
    ]
