# Generated by Django 5.1.15 on 2026-06-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('provider', models.CharField(default='daily', max_length=20)),
                ('room_name', models.CharField(max_length=120)),
                ('room_url', models.URLField()),
                ('token_paciente', models.TextField()),
                ('token_psicologa', models.TextField()),
                ('expira_em', models.DateTimeField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_room', to='scheduling.appointment')),
            ],
            options={
                'verbose_name': 'sala de vídeo',
                'verbose_name_plural': 'salas de vídeo',
            },
        ),
    ]
