# Generated by Django 5.1.15 on 2026-06-16 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('genero', models.CharField(blank=True, max_length=40, verbose_name='gênero')),
                ('queixa_principal', models.TextField(blank=True, verbose_name='queixa principal')),
                ('contato_emergencia_nome', models.CharField(blank=True, max_length=150)),
                ('contato_emergencia_telefone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('ALTA', 'Alta')], default='ATIVO', max_length=10)),
                ('inicio_tratamento', models.DateField(default=django.utils.timezone.localdate, verbose_name='início do tratamento')),
                ('valor_sessao', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='valor da sessão')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ('user__nome',),
            },
        ),
    ]
