# Generated by Django 5.1.15 on 2026-06-16 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('TERMOS_USO', 'Termos de uso'), ('PRIVACIDADE', 'Política de privacidade (LGPD)'), ('TELEATENDIMENTO', 'Consentimento de teleatendimento (CFP)')], max_length=30)),
                ('versao', models.CharField(default='1.0', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consentimento',
                'verbose_name_plural': 'consentimentos',
                'constraints': [models.UniqueConstraint(fields=('user', 'tipo', 'versao'), name='unique_consent_per_version')],
            },
        ),
    ]
