# Generated by Django 5.1.15 on 2026-06-29 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('FALHOU', 'Falhou'), ('ESTORNADO', 'Estornado')], default='PENDENTE', max_length=12)),
                ('metodo', models.CharField(choices=[('PIX', 'Pix'), ('CARTAO', 'Cartão'), ('MANUAL', 'Manual (externo)')], default='PIX', max_length=12)),
                ('provider', models.CharField(default='mercadopago', max_length=20)),
                ('provider_payment_id', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.TextField(blank=True)),
                ('qr_code_base64', models.TextField(blank=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='scheduling.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['patient', '-created_at'], name='pay_patient_created_idx')],
            },
        ),
    ]
