# Generated by Django 5.1.15 on 2026-06-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='link_pagamento',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
