# Generated by Django 5.1.15 on 2026-06-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodentry',
            options={'ordering': ('-data', '-created_at'), 'verbose_name': 'registro de humor', 'verbose_name_plural': 'registros de humor'},
        ),
        migrations.RemoveConstraint(
            model_name='moodentry',
            name='unique_mood_per_patient_day',
        ),
    ]
