# Generated by Django 5.1.15 on 2026-06-16 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('modalidade', models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial')], default='PRESENCIAL', max_length=12)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'disponibilidade',
                'verbose_name_plural': 'disponibilidades',
                'ordering': ('dia_semana', 'hora_inicio'),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_hora', models.DateTimeField()),
                ('duracao_min', models.PositiveIntegerField(default=50)),
                ('modalidade', models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial')], max_length=12)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('REALIZADA', 'Realizada'), ('FALTA', 'Falta'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=12)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'atendimento',
                'verbose_name_plural': 'atendimentos',
                'ordering': ('-data_hora',),
                'indexes': [models.Index(fields=['status', 'data_hora'], name='scheduling__status_d53618_idx')],
            },
        ),
    ]
